FROM docker.io/library/rust:1.87 AS buildbase
WORKDIR /src
RUN apt-get update && apt-get install -y git clang
RUN rustup target add wasm32-wasip1

# This line installs WasmEdge including the AOT compiler
RUN curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash

FROM buildbase AS build
COPY Cargo.toml .
COPY src ./src 
# Build the Wasm binary
RUN cargo build --target wasm32-wasip1 --release
# This line builds the AOT Wasm binary
RUN /root/.wasmedge/bin/wasmedgec target/wasm32-wasip1/release/sales_tax_rate_lookup.wasm sales_tax_rate_lookup.wasm

FROM scratch
ENTRYPOINT [ "/sales_tax_rate_lookup.wasm" ]
COPY --from=build /src/sales_tax_rate_lookup.wasm /sales_tax_rate_lookup.wasm
